[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24.7.0"
  # 修改为你自己的域名
  SITE_URL = "https://your-domain.com"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
